const venues=['桐生','戸田','江戸川','平和島','多摩川','浜名湖','蒲郡','常滑','津','三国','びわこ','住之江','尼崎','鳴門','丸亀','児島','宮島','徳山','下関','若松','芦屋','福岡','唐津','大村'];
let state={venue:null,race:null,entries:[],bets:[]};
const $=id=>document.getElementById(id);
const today=new Date();$('todayLabel').textContent=today.toLocaleDateString('ja-JP');
function init(){renderVenues();renderStats();$('backVenue').onclick=()=>show('venue');$('backRace').onclick=()=>show('race');$('sampleBtn').onclick=sample;$('calcBtn').onclick=calculate;$('saveBtn').onclick=saveRace;$('reflectBtn').onclick=reflect;$('resetBtn').onclick=()=>{if(confirm('保存データを消しますか？')){localStorage.removeItem('boat_ai_records');renderStats();}};}
function renderVenues(){ $('venueGrid').innerHTML=venues.map(v=>`<button class="venue">${v}</button>`).join(''); document.querySelectorAll('.venue').forEach(b=>b.onclick=()=>selectVenue(b.textContent)); }
function selectVenue(v){state.venue=v;$('venueTitle').textContent=`${v} レース選択`;$('raceGrid').innerHTML=Array.from({length:12},(_,i)=>`<button class="race">${i+1}R</button>`).join('');document.querySelectorAll('.race').forEach((b,i)=>b.onclick=()=>selectRace(i+1));show('race');}
function selectRace(r){state.race=r;$('raceTitle').textContent=`${state.venue} ${r}R AI予想`;state.entries=defaultEntries();renderEntryTable();$('probList').innerHTML='';$('betsTable').querySelector('tbody').innerHTML='';$('aiDecision').textContent='未計算';show('analysis');}
function show(s){$('raceSection').classList.toggle('hidden',s!=='race');$('analysisSection').classList.toggle('hidden',s!=='analysis');document.querySelector('.panel').classList.toggle('hidden',s!=='venue');}
function defaultEntries(){return [1,2,3,4,5,6].map(n=>({boat:n,name:`選手${n}`,class:'A1',nat:5.5,local:5.3,st:.16,motor:35,boatRate:34,exhibition:6.80,tilt:0,weight:52}));}
function renderEntryTable(){const tb=$('entryTable').querySelector('tbody');tb.innerHTML=state.entries.map((e,i)=>`<tr>${['boat','name','class','nat','local','st','motor','boatRate','exhibition','tilt','weight'].map(k=>`<td><input data-i="${i}" data-k="${k}" value="${e[k]}"></td>`).join('')}</tr>`).join('');tb.querySelectorAll('input').forEach(inp=>inp.oninput=()=>{let v=inp.value; if(!['name','class'].includes(inp.dataset.k)) v=parseFloat(v)||0; state.entries[inp.dataset.i][inp.dataset.k]=v;});}
function sample(){const names=['池田浩二','毒島誠','峰竜太','白井英治','桐生順平','瓜生正義'];state.entries=defaultEntries().map((e,i)=>({...e,name:names[i],nat:[7.2,6.8,7.6,6.4,6.9,6.1][i],local:[6.8,6.2,7.0,6.0,6.6,5.8][i],st:[.13,.15,.14,.16,.12,.18][i],motor:[42,31,38,36,28,33][i],boatRate:[39,34,37,32,29,30][i],exhibition:[6.71,6.79,6.73,6.82,6.75,6.86][i]}));renderEntryTable();}
function score(e){let s=0;s+=e.nat*8;s+=e.local*5;s+=e.motor*.45;s+=e.boatRate*.25;s+=(.22-e.st)*180;s+=(6.9-e.exhibition)*55;s+=[18,8,3,0,-4,-8][e.boat-1];const wind=parseFloat($('windSpeed').value)||0;if(wind>=5&&e.boat===1)s-=5;if(wind>=5&&[3,4,5].includes(e.boat))s+=2;return Math.max(1,s);}
function calculate(){const scores=state.entries.map(e=>score(e));const sum=scores.reduce((a,b)=>a+b,0);state.entries.forEach((e,i)=>{e.score=scores[i];e.p1=scores[i]/sum; e.p2=Math.min(.95,e.p1*1.65); e.p3=Math.min(.99,e.p1*2.2);});renderProb();makeBets();renderBets();decision();}
function renderProb(){const list=[...state.entries].sort((a,b)=>b.p1-a.p1);$('probList').innerHTML=list.map(e=>`<div class="prob-row"><b>${e.boat}号艇</b><div><div>${e.name}</div><div class="bar"><span style="width:${e.p1*100}%"></span></div></div><span>1着 ${(e.p1*100).toFixed(1)}%</span><span>2内 ${(e.p2*100).toFixed(1)}%</span><span>3内 ${(e.p3*100).toFixed(1)}%</span></div>`).join('');}
function makeBets(){let bets=[];for(let a of state.entries)for(let b of state.entries)for(let c of state.entries){if(new Set([a.boat,b.boat,c.boat]).size<3)continue;let p=a.p1*(b.p2/2)*(c.p3/3);let odds=autoOdds(p);bets.push({mark:`${a.boat}-${b.boat}-${c.boat}`,p,odds,ev:p*odds*100});}state.bets=bets.sort((x,y)=>y.ev-x.ev);}
function autoOdds(p){return Math.max(3,Math.min(250,Math.round((0.78/p)/1)*1));}
function renderBets(){const tb=$('betsTable').querySelector('tbody');tb.innerHTML=state.bets.slice(0,30).map((b,i)=>`<tr><td>${i+1}</td><td><b>${b.mark}</b></td><td>${(b.p*100).toFixed(2)}%</td><td><input data-mark="${b.mark}" class="odds" type="number" step="0.1" value="${b.odds}"></td><td>${b.ev.toFixed(0)}</td><td class="${b.ev>=120?'buy':b.ev>=100?'watch':'skip'}">${b.ev>=120?'買い候補':b.ev>=100?'注意':'買わない'}</td></tr>`).join('');tb.querySelectorAll('.odds').forEach(inp=>inp.oninput=()=>{let b=state.bets.find(x=>x.mark===inp.dataset.mark);b.odds=parseFloat(inp.value)||0;b.ev=b.p*b.odds*100;renderBets();decision();});}
function decision(){let top=state.bets[0];let d=$('aiDecision'),r=$('aiReason');if(!top){d.textContent='未計算';return}if(top.ev>=120){d.textContent=`購入候補 ${top.mark}`;d.className='decision buy';r.textContent=`期待値 ${top.ev.toFixed(0)}。ただし実戦は資金管理必須。`;}else if(top.ev>=100){d.textContent='注意して少額';d.className='decision watch';r.textContent=`最高期待値 ${top.ev.toFixed(0)}。無理買いは避ける。`;}else{d.textContent='見送り推奨';d.className='decision skip';r.textContent='期待値120以上なし。';}}
function saveRace(){if(!state.venue||!state.race)return alert('レースを選択してください');let records=getRecords();records.push({date:today.toISOString().slice(0,10),venue:state.venue,race:state.race,entries:state.entries,bets:state.bets.slice(0,10),createdAt:Date.now()});localStorage.setItem('boat_ai_records',JSON.stringify(records));alert('保存しました');renderStats();}
function reflect(){let result=$('finalResult').value.trim();let payout=parseInt($('payout').value)||0;let stake=parseInt($('stake').value)||0;let top=state.bets[0];if(!top)return alert('先にAI計算してください');let hit=top.mark===result;let profit=hit?payout-stake:-stake;$('reflectResult').textContent=hit?`的中 +${profit.toLocaleString()}円`:`不的中 ${profit.toLocaleString()}円`;let records=getRecords();records.push({date:today.toISOString().slice(0,10),venue:state.venue,race:state.race,buy:top.mark,result,hit,payout,stake,profit,ev:top.ev,createdAt:Date.now()});localStorage.setItem('boat_ai_records',JSON.stringify(records));renderStats();}
function getRecords(){return JSON.parse(localStorage.getItem('boat_ai_records')||'[]');}
function renderStats(){let rs=getRecords().filter(r=>'stake'in r);let stake=rs.reduce((a,r)=>a+r.stake,0),pay=rs.reduce((a,r)=>a+r.payout,0),hit=rs.filter(r=>r.hit).length,profit=rs.reduce((a,r)=>a+r.profit,0);$('stats').innerHTML=`<div class="stat">件数<b>${rs.length}</b></div><div class="stat">的中率<b>${rs.length?(hit/rs.length*100).toFixed(1):0}%</b></div><div class="stat">回収率<b>${stake?(pay/stake*100).toFixed(1):0}%</b></div><div class="stat">総収支<b>${profit.toLocaleString()}円</b></div>`;}
init();
