PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS venues (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  venue_id TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL DEFAULT '',
  region TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS races (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  race_key TEXT NOT NULL UNIQUE,
  race_date TEXT NOT NULL,
  venue_id TEXT NOT NULL,
  race_no INTEGER NOT NULL,
  title TEXT NOT NULL DEFAULT '',
  grade TEXT NOT NULL DEFAULT '',
  deadline TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT '',
  is_final INTEGER NOT NULL DEFAULT 0,
  raw_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(race_date, venue_id, race_no),
  FOREIGN KEY (venue_id) REFERENCES venues(venue_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS entries (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  race_id INTEGER NOT NULL,
  lane INTEGER NOT NULL,
  registration_no TEXT NOT NULL DEFAULT '',
  racer_name TEXT NOT NULL DEFAULT '',
  branch TEXT NOT NULL DEFAULT '',
  age INTEGER NOT NULL DEFAULT 0,
  weight REAL NOT NULL DEFAULT 0,
  f_count INTEGER NOT NULL DEFAULT 0,
  l_count INTEGER NOT NULL DEFAULT 0,
  avg_start_t REAL NOT NULL DEFAULT 0,
  exhibition_time REAL NOT NULL DEFAULT 0,
  motor_no TEXT NOT NULL DEFAULT '',
  boat_no TEXT NOT NULL DEFAULT '',
  raw_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(race_id, lane),
  FOREIGN KEY (race_id) REFERENCES races(id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS results (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  race_id INTEGER NOT NULL UNIQUE,
  order_text TEXT NOT NULL DEFAULT '',
  kimarite TEXT NOT NULL DEFAULT '',
  finishers_json TEXT NOT NULL DEFAULT '[]',
  payouts_json TEXT NOT NULL DEFAULT '[]',
  raw_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (race_id) REFERENCES races(id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS weather (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  race_id INTEGER NOT NULL UNIQUE,
  weather TEXT NOT NULL DEFAULT '',
  wind_direction TEXT NOT NULL DEFAULT '',
  wind_speed REAL NOT NULL DEFAULT 0,
  wave_height REAL NOT NULL DEFAULT 0,
  air_temperature REAL NOT NULL DEFAULT 0,
  water_temperature REAL NOT NULL DEFAULT 0,
  raw_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (race_id) REFERENCES races(id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS motors (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  race_id INTEGER NOT NULL,
  lane INTEGER NOT NULL,
  motor_no TEXT NOT NULL DEFAULT '',
  two_rate REAL NOT NULL DEFAULT 0,
  three_rate REAL NOT NULL DEFAULT 0,
  raw_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(race_id, lane),
  FOREIGN KEY (race_id) REFERENCES races(id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS boats (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  race_id INTEGER NOT NULL,
  lane INTEGER NOT NULL,
  boat_no TEXT NOT NULL DEFAULT '',
  two_rate REAL NOT NULL DEFAULT 0,
  three_rate REAL NOT NULL DEFAULT 0,
  raw_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(race_id, lane),
  FOREIGN KEY (race_id) REFERENCES races(id)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_races_date ON races(race_date);
CREATE INDEX IF NOT EXISTS idx_races_venue ON races(venue_id);
CREATE INDEX IF NOT EXISTS idx_entries_race_id ON entries(race_id);
CREATE INDEX IF NOT EXISTS idx_motors_race_id ON motors(race_id);
CREATE INDEX IF NOT EXISTS idx_boats_race_id ON boats(race_id);
